spring.application.name=AiServices
spring.mongodb.uri=mongodb://localhost:27017/AI_Services
spring.mongodb.database=AI_Services
server.port=8082
eureka.client.service-url.defaultzone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=activity-processor-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.properties.spring.json.use.type.headers=false
spring.kafka.properties.spring.json.value.default.type=com.fitness.AiServices.model.Activity
spring.kafka.properties.spring.json.trusted.packages="*"
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
kafka.topic.name=activity-events